### ISSUE TITLE
Intero suppresses GHC warnings from flycheck.

### ISSUE THREAD

**Issue by crocket** [commercialhaskell/intero#143]
With only haskell-mode and flycheck, I can see lots of warnings on my haskell source codes.
If I add intero, all warnings are suppressed.

How can I see warnings with intero?

**Comment by chrisdone** [comment]
Try adding this to the top of your file:

`{-# OPTIONS -Wall #-}`

Does it  change anything?

**Comment by crocket** [comment]
With `{-# OPTIONS -Wall #-}` at the top of a source code, emacs displays warnings at the right spots.

**Comment by chrisdone** [comment]
You just need to enable warnings in your cabal file then. :)

**Comment by crocket** [comment]
I added `-Wall` to `ghc-options` in my cabal file. But, after I restart emacs, intero still doesn't show warnings until I save a source code.

**Comment by chrisdone** [comment]
Flycheck has its own Haskell checker which specifies `-Wall` as a way to get the most checking information.

After intero is booted up it's supposed to trigger a flycheck on the buffer. Is that not happening?

**Comment by crocket** [comment]
I can reproduce the issue with intero 0.1.15 from melpa-stable and intero-20160710.2349 from melpa.
If I open a haskell source file before intero is booted up, the source file's buffer triggers intero, and intero doesn't display warnings until I edit the buffer.

Also, flycheck alone displays all warnings, but intero suppresses `some` warnings.

**Comment by chrisdone** [comment]
@crocket I fixed a warning parsing bug while working on something. Perhaps this fixes your problem?

**Comment by crocket** [comment]
No. If intero was booted up after I opened a source file, I would have to do some editing before warnings show up.

**Comment by chrisdone** [comment]
Want to give me an example project?

**Comment by crocket** [comment]
You can test intero with https://github.com/crocket/my-haskell-project/blob/master/src/learn.hs

**Comment by crocket** [comment]
After the fix, I can see all the warnings, but the warnings are still not shown if intero is booted up in a haskell source code until I edit the buffer.

**Comment by pbogdan** [comment]
I'm seeing a similar, perhaps same, issue here:

1. When I open a file for the first time no warnings are shown until the buffer is changed
2. if I revert the buffer with `(revert-buffer)` I'm back to 1. with no warnings shown.

However if at that point I remove the following folders:

- /tmp/ghc*
- /tmp/ghci*
- /tmp/intero*

then it fixes 2. from there on and the warnings are shown immediately after reverting the buffer without having to make any changes.

**Comment by pbogdan** [comment]
So in my case when intero first boots up I see the following happening:

- intero starts up, runs flycheck and loads the current module. This produces warnings as expected.
- for whatever reason, immediately after the first flycheck run a second one is triggered. Since the file/module hasn't changed the file/module is not recompiled so loading it produces no warnings, this clears any warnings from the first run

For reverting the buffer it's similar, intero seems to be automatically saving the file whenever a change is made so reverting it makes no changes, on revert module is reloaded but again not recompiled, produces no warnings and clears any produced previously.

**Comment by pbogdan** [comment]
a work around that seems to work for me and forces recompilation; not sure how it affects performance but should be fine on small projects

```elisp
(defadvice
    intero-start-process-in-buffer
    (after intero-force-recomp)
  (process-send-string (intero-process 'backend) ":set -fforce-recomp\n"))
```

**Comment by chrisdone** [comment]
I've found a bug which seems similar. Sometimes flycheck will request errors twice, and the first will suceed with warnings, but the second will be cached because there's no change to the file, so `:l X.hs` returns OK, with no warnings.

You can test it like this. Enable intero debugging: `(intero-toggle-debug)`

Get the temp filename: `(intero-temp-file-name)`

```
(intero-blocking-call 'backend ":l <the temp file>")
```

You'll see if you call it twice that the second time yields no warnings. 

Call `(shell-command-to-string "touch <the temp file>")` and you'll see the warnings again.

**Comment by chrisdone** [comment]
Okay, I've figured it out. It's here:
``` elisp
(intero-async-call
       'backend
       (concat ":l " (intero-localize-path (intero-temp-file-name nil t)))
```

The `intero-temp-file-name` function writes the buffer to the file, but `intero-async-call` can queue up a few calls in succession so the order is likely like this:

```
1. Write file X.hs
2. Write file X.hs
3. `:l X.hs` - get warnings
4. `:l X.hs` - get nothing, because there's no save
```

I think I'll take a page from my own book working on haskell-interactive-mode, some commands (like this one) need to do an action exactly in order before it sends something to the GHCi process. So I'd pass in a function to be run when the queued up command was at the head of the queue. I think I can just have `intero-async-call` support a string or a function as the command to run. If it's a function, just run the function and then what it returns is the command.

**Comment by borkdude** [comment]
Is this going to be fixed?

**Comment by purcell** [comment]
@borkdude Some of this is already fixed, in that intero now never saves the file for you, so the revert issue mentioned by @pbogdan above should be gone.

However, the occasional race condition scenario when two identical flychecks run in quick success is still present, and there's no easy fix. It's not enough to simply touch the temp file before each `:l`, because both `:l` commands might only reach the backend after the second `touch` (or elisp equivalent, `set-file-times`).

Another workaround would be to note the temp file's modtime and its flycheck results, and then later replay those results rather than the actual results from the backend. This seems pretty hacky, though.

Ultimately, what's probably wanted is to force each `:l` to recompile the given file, as per @pbogdan's `:set -fforce-recomp` suggestion. Any reason for us not to pass that along with the existing backend command in `intero-check`, @chrisdone?

**Comment by chrisdone** [comment]
@purcell forcing recompilation will force all the dependent modules which would remove the only thing that makes intero fast.

**Comment by chrisdone** [comment]
The fix in haskell-process.el was when queuing up a command, you also queue up an action to run just before. So with that in place, you could queue up an action to save the file again just before running `:l`. I started adding that to intero but didn't succeed. Emacs Lisp is hard to refactor. 🙈 

Another option is if `intero` itself touches the file inside the `:l` command. That might be easier. The only reason to `:l` a module by name is because you changed it and want to load it. That would leave dependent files cached.

**Comment by purcell** [comment]
Thanks, I might take a look at that former approach, then. Emacs has `set-file-times`, which I think constitutes a cross-platform `touch`. But the latter change also sounds reasonable.

**Comment by purcell** [comment]
> The fix in haskell-process.el was when queuing up a command, you also queue up an action to run just before. So with that in place, you could queue up an action to save the file again just before running :l. I started adding that to intero but didn't succeed. Emacs Lisp is hard to refactor. 🙈

I took a look at this, and I see that `intero` immediately sends all backend requests through to the child process, so they're effectively queued in the backend. So we'd indeed have to switch to queuing up commands on the Emacs side and then only dispatching the next once the first has been executed, so that an elisp action could be called just beforehand. Yes, looks fiddly, but I was scared away by the backend code...

**Comment by chrisdone** [comment]
In that case perhaps patching Intero's `:load` to do a `touch` before-hand (or making a `:check` command to do the same) would be reasonable. All things being the same I'd prefer to keep the Elisp simpler and more reliable.

**Comment by chrisdone** [comment]
Opened PR for that here: https://github.com/commercialhaskell/intero/pull/421

**Comment by chrisdone** [comment]
I changed my mind. Fixing it in intero.el seems like the only way to be sure.

**Comment by chrisdone** [comment]
That doesn't seem to work either: https://github.com/commercialhaskell/intero/pull/422

**Comment by chrisdone** [comment]
Now I'm beginning to think that GHC doesn't reload a file if its modification time differs by <1 second.

I'm about ready to give up on this.

**Comment by chrisdone** [comment]
Some reproducible evidence:

```
bash-3.2$ (echo ':!touch Main.hs'; echo ':l Main.hs'; echo ':!touch Main.hs'; echo ':l Main.hs') | stack exec -- ghci -fobject-code
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> [1 of 1] Compiling Main             ( Main.hs, Main.o )

Main.hs:2:1: Warning:
    Top-level binding with no type signature: x :: Integer

Main.hs:2:5: Warning:
    Defaulting the following constraint(s) to type ‘Integer’
      (Num a0) arising from the literal ‘1’
    In the expression: 1
    In an equation for ‘x’: x = 1
Ok, modules loaded: Main.
Prelude Main> Prelude Main> Ok, modules loaded: Main.
Prelude Main> Leaving GHCi.
```

So either one of the following are true:

* GHC's dirtiness checker is at second-level granularity.
* The `touch` and `set-file-times` commands (implemented with utime, perhaps) are specifying at seconds level of granularity.

From the `utime` docs, I see

>  The utime() system call allows specification of timestamps with a resolution of 1 second.
>
 >  The utimes() system call is similar, but the times argument refers to    an array rather than a structure.  The elements of this array are  timeval structures, which allow a precision of 1 microsecond for   specifying timestamps.

My implementation with Intero was using `touchFile`:

``` haskell
touchFile :: FilePath -> IO ()
touchFile name = do
  withFilePath name $ \s ->
   throwErrnoPathIfMinus1_ "touchFile" name (c_utime s nullPtr)
```

So perhaps that's the issue.

Additionally, in Emacs, `set-file-times` is implemented with this code: https://github.com/jwiegley/emacs-release/blob/adfd5933358fdf6715423dee8169eb3cd7d982db/lib/utimens.c#L289

It's not clear whether that's setting nanosecond time either without further delving.

**Comment by purcell** [comment]
@chrisdone It turns out that we are already updating the temp file time stamp (to the nearest millisecond) every time we request it, so the file _should_ look permanently new to `:l`. When you call `M-x normal-mode` on a buffer with warnings - which is a good test-case for this issue - two flychecks are run in quick succession, and the latter always sees a slightly later timestamp on the temp file. This is all consistent with your findings, then, and makes it hard to work around robustly. (Separately, I wonder why two flychecks are run...)

**Comment by purcell** [comment]
Okay, I think I have a working solution in #423...

**Comment by chrisdone** [comment]
This fixes it for me. Nice work @purcell!

**Comment by crocket** [comment]
I still need to add `ghc-options: -Wall` to `package.yaml` in order to see all warnings in source files. Is this the intended behavior?
