### ISSUE TITLE
Intero cannot find `Paths_*` module

### ISSUE THREAD

**Issue by passy** [commercialhaskell/intero#288]
Hi there, I hope I'm not missing something obvious.

If I try to load a module that references an auto-generated `Paths_*` module, I get an error from intero, while `stack repl` is happy to load it for me.

<img width="612" alt="screenshot 2016-10-16 08 45 40" src="https://cloud.githubusercontent.com/assets/9906/19418661/29465ec0-937d-11e6-9c1f-12381ef985c0.png">

Is this expected?

**Comment by chrisdone** [comment]
Right, a `stack build` first should sort this. I think this'll be fixed in the next stack release.

**Comment by passy** [comment]
Cool, I'll try again with the next version. Right now, a `stack build` doesn't help unfortunately.

**Comment by mgsloan** [comment]
Surprising that a `stack build` doesn't help.  But yes, the next version of stack will make the `--no-build` flag unnecessary, because it will only do some initial build steps (run preprocessors and generate file like `Paths_*.hs`)

**Comment by chrisdone** [comment]
@passy The latest release should have this fixed. :clamp:

**Comment by deepfire** [comment]
@chrisdone, I have stack 1.3.2 and intero 0.1.20, and I still have this problem. What should I try?

**Comment by chrisdone** [comment]
I just noticed the guy was using `stack exec intero`. It should be `stack ghci --with-ghc intero`

**Comment by passy** [comment]
@chrisdone @deepfire I was using the emacs integration back then, but wanted to have a more minimal test case - which is why I tried `stack exec`.

**Comment by chrisdone** [comment]
`stack ghci` calls `stack build` implicitly creating the `Paths_` file. Intero would call it with `--no-build`, therefore not creating the file. Then @mgsloan made it so it'd generate those things anyway without needing a full build in the recent stack.

So `stack exec` would never do any of that good setup stuff. And intero itself doesn't look at your package's config, it relies on stack to call it in the right way.

**Comment by passy** [comment]
@chrisdone Gotcha! Thanks for the explanation!

**Comment by deepfire** [comment]
@chrisdone, so.. I still feel like I'm in the dark as to how to proceed..

**Comment by chrisdone** [comment]
@deepfire Can you provide a test case?
